In [7]:
import cv2
import numpy as np

image = cv2.imread('images/input.jpg', 0)
#0 signifies loading a grayscale image 
cv2.imshow("original",image)
print(image)
# creating a  mask that needs to be added to the original image
# This gives a matrix with same dimesions of our image with all values being 120
mask = np.ones(image.shape, dtype = "uint8") * 120 
print(mask)

# increasing the brightness
inc_bright = cv2.add(image, mask)
cv2.imshow("brightness increased", inc_bright)
print(inc_bright)
# direct method
added2 = image + mask
cv2.imshow("Added 2", added2)
print(added2)
# we notice that in direct method it does not have a max ceiling value instead 
# restarts the pixel value from 0 once it exceeds 255
cv2.waitKey(0)
cv2.destroyAllWindows()

[[228 227 227 ... 249 249 249]
 [227 227 227 ... 248 248 248]
 [227 227 227 ... 247 247 247]
 ...
 [189 180 169 ... 202 192 185]
 [199 203 181 ... 197 188 181]
 [204 202 195 ... 195 188 176]]
[[120 120 120 ... 120 120 120]
 [120 120 120 ... 120 120 120]
 [120 120 120 ... 120 120 120]
 ...
 [120 120 120 ... 120 120 120]
 [120 120 120 ... 120 120 120]
 [120 120 120 ... 120 120 120]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[ 92  91  91 ... 113 113 113]
 [ 91  91  91 ... 112 112 112]
 [ 91  91  91 ... 111 111 111]
 ...
 [ 53  44  33 ...  66  56  49]
 [ 63  67  45 ...  61  52  45]
 [ 68  66  59 ...  59  52  40]]
